services:
  stats-db:
    container_name: stats-db
    image: postgres:16-alpine
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-stats_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./data/stats-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  core-db:
    container_name: core-db
    image: postgres:16-alpine
    ports:
      - "8432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./data/core:/var/lib/postgresql/data
    entrypoint: >
      sh -c "
      echo 'CREATE DATABASE event_service;
      CREATE DATABASE user_service;
      CREATE DATABASE comment_service;
      CREATE DATABASE request_service;' > /docker-entrypoint-initdb.d/init.sql;
      exec docker-entrypoint.sh postgres
      "
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure