spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main-service-route
          uri: lb://main-service
          predicates:
            - Path=/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

server:
port: 8080