server:
  port: 0

spring:
  application:
    name: stats-client

grpc:
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext