spring:
  application:
    name: analyzer
  main:
    banner-mode: off

  kafka:
    bootstrap-servers: ${SERVER_KAFKA_ADDRESS:localhost:9092}

    consumer:
      properties:
        "bootstrap.servers": ${spring.kafka.bootstrap-servers}
        "group.id": aggregator-action-group
        "auto.offset.reset": earliest
        "enable.auto.commit": false

    producer:
      properties:
        "bootstrap.servers": ${spring.kafka.bootstrap-servers}
        "client.id": aggregator-producer
        "acks": 1
        "key.serializer": "org.apache.kafka.common.serialization.StringSerializer"
        "value.serializer": "ru.practicum.serializer.AvroSerializer"
        "linger.ms": 0
  data:
    jdbc:
      dialect: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6542/stats_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      connection-timeout: 5000
      initialization-fail-timeout: 0
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema-init.sql
  jpa:
    hibernate:
      ddl-auto: update
      dialect:
    show-sql: true

grpc:
  server:
    port: 0

server:
  kafka:
    topic-config:
      user-actions: stats.user-actions.v1
      events-similarity: stats.events-similarity.v1
    consumer:
      poll-timeout-ms: 100
      batch-messages-count: 10

logging:
  level:
    ru.yandex: TRACE
    org:
      springframework: ERROR
      apache.kafka: WARN